### ISSUE TITLE
你好 固体变换的一章重复了3d变换一章的内容

### ISSUE THREAD

**Issue by PangPangPangPangPang** [ZsIsMe/ios_core_animation_advanced_techniques#1]
rt

**Comment by PangPangPangPangPang** [comment]
我下载的是pdf版本~

**Comment by ZsIsMe** [comment]
我找不到你说的那个错误啊？请问可以说的详细点么？
没有固体变换的那一章啊 ？你可以把重复的内容黏贴出来么？谢谢！

**Comment by PangPangPangPangPang** [comment]
好吧  下载的是pdf版本 然后用mac ibook 看的时候 固体对象一章 内容跟 3d变换一章内容重复  但是同一个pdf在家用pad 的adobe reader看没问题...
