### ISSUE TITLE
7.1事务章节代码错误

### ISSUE THREAD

**Issue by tbago** [ZsIsMe/ios_core_animation_advanced_techniques#4]
@property (nonatomic, weak) IBOutlet CALayer *colorLayer;
这行代码错误，首先不需要IBOutlet，同时不应该采用weak来保存对象，否则程序无法正常运行。
应该改成
@property (nonatomic, strong) CALayer *colorLayer;

**Comment by tbago** [comment]
清单7.6 实现自定义行为，存在同样问题。

**Comment by ZsIsMe** [comment]
你好，我在http://ptgmedia.pearsoncmg.com/images/9780133440751/downloads/Lockwood-Code-Projects.zip   下载了源码发现的确有以上的问题，（原版）按你的说法修改后可运行。我会在gitbook写上注释的，谢谢。
